# Configuration file for NGS QC Pipeline

# Input/output directories
input_dir: "data"  # Directory containing input FASTQ files
results_dir: "results"  # Main results directory

# Processing parameters
fastqc_threads: 4  # Number of threads for FastQC

# Uncomment and modify to specify samples manually
# samples:
#   "SampleA":
#     type: "paired"  # paired or single
#   "SampleB":
#     type: "single"